Repository pratik-choudhari/AlgoCode, pull requests merged in 2020-10, with the labels that each got.

#40 Internet Speed Test in Python(GUI)
  Python/Speedtestappwithgui/README.md
  Python/Speedtestappwithgui/SpeedTestWithGUI.py
  Python/Speedtestappwithgui/requirements.txt
Labels: incomplete

#54 spiralmatrix.cpp
  C - C++/matrixspiral.cpp
  C - C++/matrixspiral/README.md
  C - C++/matrixspiral/matrixspiral.cpp
Labels: incomplete

#134 Adding a more simpler program to calculate factorial of large numbers
  C - C++/fatorialOfLargeNumber/README.md
  C - C++/fatorialOfLargeNumber/fact.cpp
  C - C++/fatorialOfLargeNumber/factorial.cpp
Labels: incomplete

#88 Added -> K-Combination generation wihth python
  CONTRIBUTORS.md
  Python/K-CombinationGen/README.md
  Python/K-CombinationGen/Screenshot (144).png
  Python/K-CombinationGen/main.py
Labels: incomplete

#133 Python Sudoku Solver
  Projects/Sudoku_Solver_cli/README.MD
  Projects/Sudoku_Solver_cli/sudoku_main.py
Labels: incomplete

#144 Rotate array using Java standard libraries
  CONTRIBUTORS.md
  Java/ArrayRotator/ArrayRotator.java
  Java/ArrayRotator/REDME.md
Labels: incomplete

#152 Closest 9's and 0's multiple
  C - C++/Closest 9's and 0's multiple/Closest 9's and 0's multiple.cpp
  C - C++/Closest 9's and 0's multiple/README.md
Labels: incomplete

#158 Added the S&P 500 Companies Scraper Project
  Projects/S&P 500 Companies Scraper/.gitignore
  Projects/S&P 500 Companies Scraper/README.md
  Projects/S&P 500 Companies Scraper/demo.jpg
  Projects/S&P 500 Companies Scraper/main.py
  Projects/S&P 500 Companies Scraper/requirements.txt
Labels: incomplete

#163 Generate all binary strings from given pattern #147
  C - C++/Generate all binary strings from given pattern/README.md
  C - C++/Generate all binary strings from given pattern/recursive.cpp
  C - C++/Remove large Spaces between String/README.md
  C - C++/Remove large Spaces between String/solve.cpp
Labels: incomplete

#157 To do list using html css and javascript
  Projects/To_do_list/To_Do_list.html
Labels: incomplete

#130 Sequence sum modified
  Java/Sum of a sequence/README.md
  Java/Sum of a sequence/SequenceSum.java
  Java/Sum of a sequence/SeuqeunceSumModified.java
Labels: incomplete

#180 Create Min. triangle height
  CONTRIBUTORS.md
  Python/Min. Triangle Height/Min. Triangle Height.py
  Python/Min. Triangle Height/README.md
Labels: incomplete

#184 Rock - Paper - Scissor Game
  Javascript/RockPaperScissor/Readme.md
  Javascript/RockPaperScissor/index.js
Labels: early bird

#225 sqlite CRUD opertion added in python
  Python/Sqlite/README.md
  Python/Sqlite/sqlite_crud.py
  Python/Sqlite/testdb.sqlite
Labels: incomplete

#300 added code for number conversion
  Python/NumberConversion/Num_convert.py
  Python/NumberConversion/README.md
Labels: awaiting changes

#283 Add merge two sorted linked list in sorted order
  C - C++/Merge_Linked_List/README.MD
  C - C++/Merge_Linked_List/merge_linked_list.c
  CONTRIBUTORS.md
Labels: incomplete

#325 Added Countdown Timer program #320
  Python/Countdown Timer/clock.ogg
  Python/Countdown Timer/countdown1.py
  Python/Countdown Timer/readme.md
  Python/Countdown Timer/requirements.txt
Labels: awaiting changes

#339 Timer with GUI using Vanilla Javascript
  Projects/Timer_GUI/README.md
  Projects/Timer_GUI/app.js
  Projects/Timer_GUI/images/ss1.png
  Projects/Timer_GUI/images/ss2.png
  Projects/Timer_GUI/images/ss3.png
  Projects/Timer_GUI/index.html
  Projects/Timer_GUI/style.css
Labels: awaiting changes

#375 Operations on an Array
  C - C++/Operations on an Array/Operations_on_an_Array.cpp
  C - C++/Operations on an Array/README.md
Labels: awaiting changes

#393 Sort an Array
  C#/Sort an Array/README.md
  C#/Sort an Array/file.CS
Labels: awaiting changes

#438 Added Titanic EDA
  EDA/Titanic_Dataset/EDA_on_Titanic_Dataset.ipynb
  EDA/Titanic_Dataset/Readme.md
  EDA/Titanic_Dataset/Requirements.txt
Labels: awaiting changes

#443 add project of timer
  Projects/Timer_Using_React/.gitignore
  Projects/Timer_Using_React/README.md
  Projects/Timer_Using_React/package.json
  Projects/Timer_Using_React/public/index.html
  Projects/Timer_Using_React/public/working_snapshots/Timer_1.png
  Projects/Timer_Using_React/public/working_snapshots/Timer_2.png
  Projects/Timer_Using_React/public/working_snapshots/Timer_3.png
  Projects/Timer_Using_React/public/working_snapshots/Timer_4.png
  Projects/Timer_Using_React/public/working_snapshots/Timer_5.png
  Projects/Timer_Using_React/src/App.js
  Projects/Timer_Using_React/src/components/View/index.js
  Projects/Timer_Using_React/src/components/View/styles.js
  Projects/Timer_Using_React/src/index.js
  Projects/Timer_Using_React/yarn.lock
Labels: awaiting changes

#465 Python GEODATA
  Python/geodata/README.md
  Python/geodata/geodata.sqlite
  Python/geodata/geodump.py
  Python/geodata/geoload.py
  Python/geodata/where.data
  Python/geodata/where.html
  Python/geodata/where.js
Labels: awaiting changes
